package SelectTur;

import java.util.Vector;


class ProvinciaFactory {

    static final int COMMADRID = 100;
    static final int MADRID = 0;
    static final int COMANDALUCIA = 200;
    static final int ALMERIA = 1;
    static final int CADIZ = 2;
    static final int CORDOBA = 3;
    static final int GRANADA = 4;
    static final int HUELVA = 5;
    static final int JAEN = 6;
    static final int MALAGA = 7;
    static final int SEVILLA = 8;
    static final int COMCATALUNA = 300;
    static final int BARCELONA = 9;
    static final int GIRONA = 10;
    static final int LLEIDA = 11;
    static final int TARRAGONA = 12;
    static final int COMVALENCIANA = 400;
    static final int ALICANTE = 13;
    static final int CASTELLON = 14;
    static final int VALENCIA = 15;
    static final int COMGALICIA = 500;
    static final int ACORUNA = 16;
    static final int LUGO = 17;
    static final int OURENSE = 18;
    static final int PONTEVEDRA = 19;
    static final int COMPAISVASCO = 600;
    static final int ALAVA = 20;
    static final int GIPUZKOA = 21;
    static final int BIZKAIA = 22;

    static final boolean CULTURA = true;
    static final boolean SOLYPLAYA = true;
    static final boolean GASTRONOMIA = true;
    private static Vector<Provincia> provincias;
    private static double[][] costoTransporte;
    static int NUMERO_PROVINCIAS;


    static void inicializar() {
        crearProvincias();
        crearCostoTransporte();
    }

    static void crearProvincias() {
        provincias = new Vector<Provincia>();
        provincias.add(new Provincia(MADRID, COMMADRID,4, new boolean[]{CULTURA, false, GASTRONOMIA},40.55));
        provincias.add(new Provincia(ALMERIA, COMANDALUCIA, 4, new boolean[]{false, SOLYPLAYA, false},27.01));
        provincias.add(new Provincia(CADIZ, COMANDALUCIA, 3, new boolean[]{false, SOLYPLAYA, false},30.04));
        provincias.add(new Provincia(CORDOBA, COMANDALUCIA, 2, new boolean[]{CULTURA, false, GASTRONOMIA},46.48));
        provincias.add(new Provincia(GRANADA, COMANDALUCIA, 3, new boolean[]{CULTURA, SOLYPLAYA, GASTRONOMIA},28.68));
        provincias.add(new Provincia(HUELVA, COMANDALUCIA, 5, new boolean[]{CULTURA, SOLYPLAYA, GASTRONOMIA},51.75));
        provincias.add(new Provincia(JAEN, COMANDALUCIA, 2, new boolean[]{false, false, GASTRONOMIA},33.24));
        provincias.add(new Provincia(MALAGA, COMANDALUCIA, 5, new boolean[]{false, SOLYPLAYA, GASTRONOMIA},37.75));
        provincias.add(new Provincia(SEVILLA, COMANDALUCIA, 3, new boolean[]{CULTURA, false, GASTRONOMIA},31.73));
        provincias.add(new Provincia(BARCELONA, COMCATALUNA, 4, new boolean[]{CULTURA, SOLYPLAYA, false},42.42));
        provincias.add(new Provincia(GIRONA, COMCATALUNA,6, new boolean[]{false, SOLYPLAYA, GASTRONOMIA},47.78));
        provincias.add(new Provincia(LLEIDA, COMCATALUNA, 7, new boolean[]{false, false, GASTRONOMIA},43.47));
        provincias.add(new Provincia(TARRAGONA, COMCATALUNA, 6, new boolean[]{false, SOLYPLAYA, false},50.35));
        provincias.add(new Provincia(ALICANTE, COMVALENCIANA, 5, new boolean[]{false, SOLYPLAYA, false},48.33));
        provincias.add(new Provincia(CASTELLON, COMVALENCIANA, 5, new boolean[]{false, SOLYPLAYA, false},66.15));
        provincias.add(new Provincia(VALENCIA, COMVALENCIANA, 4, new boolean[]{false, SOLYPLAYA, false},62.98));
        provincias.add(new Provincia(ACORUNA, COMGALICIA, 7, new boolean[]{CULTURA, SOLYPLAYA, false},39.46));
        provincias.add(new Provincia(LUGO, COMGALICIA, 2, new boolean[]{false, SOLYPLAYA, GASTRONOMIA},23.94));
        provincias.add(new Provincia(OURENSE, COMGALICIA, 4, new boolean[]{false, false, GASTRONOMIA},19.47));
        provincias.add(new Provincia(PONTEVEDRA, COMGALICIA,4, new boolean[]{false, SOLYPLAYA, false},57.44));
        provincias.add(new Provincia(ALAVA, COMPAISVASCO,2, new boolean[]{false, false, GASTRONOMIA, false},47.31));
        provincias.add(new Provincia(GIPUZKOA, COMPAISVASCO,3, new boolean[]{false, SOLYPLAYA, false},43.39));
        provincias.add(new Provincia(BIZKAIA, COMPAISVASCO,3, new boolean[]{CULTURA, SOLYPLAYA, false},39.45));

        NUMERO_PROVINCIAS = provincias.size();
    }

    private static Provincia getProvincia(int codigo) {
        return provincias.get(codigo);
    }

    static double getCostoEstadia(int codigo) {
        return getProvincia(codigo).getCostoEstadia();
    }

    static int getMaxEstadia(int codigo) {
        return getProvincia(codigo).getEstadia();
    }

    static boolean[] getPreferencias(int codigo) {
        return getProvincia(codigo).getPreferencias();
    }

    static double getCostoTransporte(int origen, int destino) {
        return costoTransporte[origen][destino];
    }

    static String getNombre(int codigo) {

        switch (codigo) {
            case 0: return "MADRID, C. DE MADRID";
            case 1: return "ALMERIA, C. DE ANDALUCIA";
            case 2: return "CADIZ, C. DE ANDALUCIA";
            case 3: return "CORDOBA, C. DE ANDALUCIA";
            case 4: return "GRANADA, C. DE ANDALUCIA";
            case 5: return "HUELVA, C. DE ANDALUCIA";
            case 6: return "JAEN, C. DE ANDALUCIA";
            case 7: return "MALAGA, C. DE ANDALUCIA";
            case 8: return "SEVILLA, C. DE ANDALUCIA";
            case 9: return "BARCELONA, C. DE CATALUNA";
            case 10: return "GIRONA, C. DE CATALUNA";
            case 11: return "LLEIDA, C. DE CATALUNA";
            case 12: return "TARRAGONA, C. DE CATALUNA";
            case 13: return "ALICANTE, C. VALENCIANA";
            case 14: return "CASTELLON, C. VALENCIANA";
            case 15: return "VALENCIA, C. VALENCIANA";
            case 16: return "ACORUNA, C. DE GALICIA";
            case 17: return "LUGO, C. DE GALICIA";
            case 18: return "OURENSE, C. DE GALICIA";
            case 19: return "PONTEVEDRA, C. DE GALICIA";
            case 20: return "ALAVA, PAIS VASCO";
            case 21: return "GIPUZKOA, PAIS VASCO";
            case 22: return "BIZKAIA, PAIS VASCO";
            default: return "ERROR DE CODIGO";
        }
    }

    private static void crearCostoTransporte() {
        costoTransporte = new double[NUMERO_PROVINCIAS][NUMERO_PROVINCIAS];

        costoTransporte[ProvinciaFactory.MADRID][ProvinciaFactory.MADRID] = 0;
        costoTransporte[ProvinciaFactory.MADRID][ProvinciaFactory.ALMERIA] = 58.36;
        costoTransporte[ProvinciaFactory.MADRID][ProvinciaFactory.CADIZ] = 81.31;
        costoTransporte[ProvinciaFactory.MADRID][ProvinciaFactory.CORDOBA] = 62.28;
        costoTransporte[ProvinciaFactory.MADRID][ProvinciaFactory.GRANADA] = 59.25;
        costoTransporte[ProvinciaFactory.MADRID][ProvinciaFactory.HUELVA] = 78.28;
        costoTransporte[ProvinciaFactory.MADRID][ProvinciaFactory.JAEN] = 41.91;
        costoTransporte[ProvinciaFactory.MADRID][ProvinciaFactory.MALAGA] = 76.29;
        costoTransporte[ProvinciaFactory.MADRID][ProvinciaFactory.SEVILLA] = 69.7;
        costoTransporte[ProvinciaFactory.MADRID][ProvinciaFactory.BARCELONA] = 83.12;
        costoTransporte[ProvinciaFactory.MADRID][ProvinciaFactory.GIRONA] = 108.14;
        costoTransporte[ProvinciaFactory.MADRID][ProvinciaFactory.LLEIDA] = 62.78;
        costoTransporte[ProvinciaFactory.MADRID][ProvinciaFactory.TARRAGONA] = 81.84;
        costoTransporte[ProvinciaFactory.MADRID][ProvinciaFactory.ALICANTE] = 55.98;
        costoTransporte[ProvinciaFactory.MADRID][ProvinciaFactory.CASTELLON] = 47.14;
        costoTransporte[ProvinciaFactory.MADRID][ProvinciaFactory.VALENCIA] = 53.34;
        costoTransporte[ProvinciaFactory.MADRID][ProvinciaFactory.ACORUNA] = 48.79;
        costoTransporte[ProvinciaFactory.MADRID][ProvinciaFactory.LUGO] = 44.41;
        costoTransporte[ProvinciaFactory.MADRID][ProvinciaFactory.OURENSE] = 35.53;
        costoTransporte[ProvinciaFactory.MADRID][ProvinciaFactory.PONTEVEDRA] = 41.08;
        costoTransporte[ProvinciaFactory.MADRID][ProvinciaFactory.ALAVA] = 49.07;
        costoTransporte[ProvinciaFactory.MADRID][ProvinciaFactory.GIPUZKOA] = 39.5;
        costoTransporte[ProvinciaFactory.MADRID][ProvinciaFactory.BIZKAIA] = 53.8;
        costoTransporte[ProvinciaFactory.ALMERIA][ProvinciaFactory.MADRID] = 58.36;
        costoTransporte[ProvinciaFactory.ALMERIA][ProvinciaFactory.ALMERIA] = 0;
        costoTransporte[ProvinciaFactory.ALMERIA][ProvinciaFactory.CADIZ] = 64.35;
        costoTransporte[ProvinciaFactory.ALMERIA][ProvinciaFactory.CORDOBA] = 69.04;
        costoTransporte[ProvinciaFactory.ALMERIA][ProvinciaFactory.GRANADA] = 23.86;
        costoTransporte[ProvinciaFactory.ALMERIA][ProvinciaFactory.HUELVA] = 97.95;
        costoTransporte[ProvinciaFactory.ALMERIA][ProvinciaFactory.JAEN] = 86.25;
        costoTransporte[ProvinciaFactory.ALMERIA][ProvinciaFactory.MALAGA] = 58.77;
        costoTransporte[ProvinciaFactory.ALMERIA][ProvinciaFactory.SEVILLA] = 59.66;
        costoTransporte[ProvinciaFactory.ALMERIA][ProvinciaFactory.BARCELONA] = 57.05;
        costoTransporte[ProvinciaFactory.ALMERIA][ProvinciaFactory.GIRONA] = 104.23;
        costoTransporte[ProvinciaFactory.ALMERIA][ProvinciaFactory.LLEIDA] = 91.4;
        costoTransporte[ProvinciaFactory.ALMERIA][ProvinciaFactory.TARRAGONA] = 80.32;
        costoTransporte[ProvinciaFactory.ALMERIA][ProvinciaFactory.ALICANTE] = 69.97;
        costoTransporte[ProvinciaFactory.ALMERIA][ProvinciaFactory.CASTELLON] = 62.17;
        costoTransporte[ProvinciaFactory.ALMERIA][ProvinciaFactory.VALENCIA] = 49.32;
        costoTransporte[ProvinciaFactory.ALMERIA][ProvinciaFactory.ACORUNA] = 161.19;
        costoTransporte[ProvinciaFactory.ALMERIA][ProvinciaFactory.LUGO] = 176.48;
        costoTransporte[ProvinciaFactory.ALMERIA][ProvinciaFactory.OURENSE] = 164.89;
        costoTransporte[ProvinciaFactory.ALMERIA][ProvinciaFactory.PONTEVEDRA] = 170.44;
        costoTransporte[ProvinciaFactory.ALMERIA][ProvinciaFactory.ALAVA] = 163.46;
        costoTransporte[ProvinciaFactory.ALMERIA][ProvinciaFactory.GIPUZKOA] = 168.86;
        costoTransporte[ProvinciaFactory.ALMERIA][ProvinciaFactory.BIZKAIA] = 160.07;
        costoTransporte[ProvinciaFactory.CADIZ][ProvinciaFactory.MADRID] = 81.31;
        costoTransporte[ProvinciaFactory.CADIZ][ProvinciaFactory.ALMERIA] = 64.35;
        costoTransporte[ProvinciaFactory.CADIZ][ProvinciaFactory.CADIZ] = 0;
        costoTransporte[ProvinciaFactory.CADIZ][ProvinciaFactory.CORDOBA] = 32.36;
        costoTransporte[ProvinciaFactory.CADIZ][ProvinciaFactory.GRANADA] = 50.58;
        costoTransporte[ProvinciaFactory.CADIZ][ProvinciaFactory.HUELVA] = 33.6;
        costoTransporte[ProvinciaFactory.CADIZ][ProvinciaFactory.JAEN] = 44.58;
        costoTransporte[ProvinciaFactory.CADIZ][ProvinciaFactory.MALAGA] = 64.33;
        costoTransporte[ProvinciaFactory.CADIZ][ProvinciaFactory.SEVILLA] = 18.02;
        costoTransporte[ProvinciaFactory.CADIZ][ProvinciaFactory.BARCELONA] = 121.53;
        costoTransporte[ProvinciaFactory.CADIZ][ProvinciaFactory.GIRONA] = 158.46;
        costoTransporte[ProvinciaFactory.CADIZ][ProvinciaFactory.LLEIDA] = 155.88;
        costoTransporte[ProvinciaFactory.CADIZ][ProvinciaFactory.TARRAGONA] = 144.8;
        costoTransporte[ProvinciaFactory.CADIZ][ProvinciaFactory.ALICANTE] = 91.08;
        costoTransporte[ProvinciaFactory.CADIZ][ProvinciaFactory.CASTELLON] = 83.28;
        costoTransporte[ProvinciaFactory.CADIZ][ProvinciaFactory.VALENCIA] = 70.43;
        costoTransporte[ProvinciaFactory.CADIZ][ProvinciaFactory.ACORUNA] = 73.54;
        costoTransporte[ProvinciaFactory.CADIZ][ProvinciaFactory.LUGO] = 134.84;
        costoTransporte[ProvinciaFactory.CADIZ][ProvinciaFactory.OURENSE] = 123.25;
        costoTransporte[ProvinciaFactory.CADIZ][ProvinciaFactory.PONTEVEDRA] = 73.18;
        costoTransporte[ProvinciaFactory.CADIZ][ProvinciaFactory.ALAVA] = 121.82;
        costoTransporte[ProvinciaFactory.CADIZ][ProvinciaFactory.GIPUZKOA] = 127.22;
        costoTransporte[ProvinciaFactory.CADIZ][ProvinciaFactory.BIZKAIA] = 118.43;
        costoTransporte[ProvinciaFactory.CORDOBA][ProvinciaFactory.MADRID] = 62.28;
        costoTransporte[ProvinciaFactory.CORDOBA][ProvinciaFactory.ALMERIA] = 69.04;
        costoTransporte[ProvinciaFactory.CORDOBA][ProvinciaFactory.CADIZ] = 32.36;
        costoTransporte[ProvinciaFactory.CORDOBA][ProvinciaFactory.CORDOBA] = 0;
        costoTransporte[ProvinciaFactory.CORDOBA][ProvinciaFactory.GRANADA] = 45.18;
        costoTransporte[ProvinciaFactory.CORDOBA][ProvinciaFactory.HUELVA] = 45.06;
        costoTransporte[ProvinciaFactory.CORDOBA][ProvinciaFactory.JAEN] = 17.21;
        costoTransporte[ProvinciaFactory.CORDOBA][ProvinciaFactory.MALAGA] = 39.51;
        costoTransporte[ProvinciaFactory.CORDOBA][ProvinciaFactory.SEVILLA] = 23.98;
        costoTransporte[ProvinciaFactory.CORDOBA][ProvinciaFactory.BARCELONA] = 123.29;
        costoTransporte[ProvinciaFactory.CORDOBA][ProvinciaFactory.GIRONA] = 97.94;
        costoTransporte[ProvinciaFactory.CORDOBA][ProvinciaFactory.LLEIDA] = 75.64;
        costoTransporte[ProvinciaFactory.CORDOBA][ProvinciaFactory.TARRAGONA] = 64.68;
        costoTransporte[ProvinciaFactory.CORDOBA][ProvinciaFactory.ALICANTE] = 63.68;
        costoTransporte[ProvinciaFactory.CORDOBA][ProvinciaFactory.CASTELLON] = 40.13;
        costoTransporte[ProvinciaFactory.CORDOBA][ProvinciaFactory.VALENCIA] = 43.03;
        costoTransporte[ProvinciaFactory.CORDOBA][ProvinciaFactory.ACORUNA] = 125.51;
        costoTransporte[ProvinciaFactory.CORDOBA][ProvinciaFactory.LUGO] = 140.8;
        costoTransporte[ProvinciaFactory.CORDOBA][ProvinciaFactory.OURENSE] = 129.21;
        costoTransporte[ProvinciaFactory.CORDOBA][ProvinciaFactory.PONTEVEDRA] = 134.76;
        costoTransporte[ProvinciaFactory.CORDOBA][ProvinciaFactory.ALAVA] = 127.78;
        costoTransporte[ProvinciaFactory.CORDOBA][ProvinciaFactory.GIPUZKOA] = 133.18;
        costoTransporte[ProvinciaFactory.CORDOBA][ProvinciaFactory.BIZKAIA] = 124.39;
        costoTransporte[ProvinciaFactory.GRANADA][ProvinciaFactory.MADRID] = 59.25;
        costoTransporte[ProvinciaFactory.GRANADA][ProvinciaFactory.ALMERIA] = 23.86;
        costoTransporte[ProvinciaFactory.GRANADA][ProvinciaFactory.CADIZ] = 50.58;
        costoTransporte[ProvinciaFactory.GRANADA][ProvinciaFactory.CORDOBA] = 45.18;
        costoTransporte[ProvinciaFactory.GRANADA][ProvinciaFactory.GRANADA] = 0;
        costoTransporte[ProvinciaFactory.GRANADA][ProvinciaFactory.HUELVA] = 89.73;
        costoTransporte[ProvinciaFactory.GRANADA][ProvinciaFactory.JAEN] = 62.39;
        costoTransporte[ProvinciaFactory.GRANADA][ProvinciaFactory.MALAGA] = 34.91;
        costoTransporte[ProvinciaFactory.GRANADA][ProvinciaFactory.SEVILLA] = 35.8;
        costoTransporte[ProvinciaFactory.GRANADA][ProvinciaFactory.BARCELONA] = 55.09;
        costoTransporte[ProvinciaFactory.GRANADA][ProvinciaFactory.GIRONA] = 128.09;
        costoTransporte[ProvinciaFactory.GRANADA][ProvinciaFactory.LLEIDA] = 89.44;
        costoTransporte[ProvinciaFactory.GRANADA][ProvinciaFactory.TARRAGONA] = 78.36;
        costoTransporte[ProvinciaFactory.GRANADA][ProvinciaFactory.ALICANTE] = 93.83;
        costoTransporte[ProvinciaFactory.GRANADA][ProvinciaFactory.CASTELLON] = 86.03;
        costoTransporte[ProvinciaFactory.GRANADA][ProvinciaFactory.VALENCIA] = 73.18;
        costoTransporte[ProvinciaFactory.GRANADA][ProvinciaFactory.ACORUNA] = 137.33;
        costoTransporte[ProvinciaFactory.GRANADA][ProvinciaFactory.LUGO] = 152.62;
        costoTransporte[ProvinciaFactory.GRANADA][ProvinciaFactory.OURENSE] = 141.03;
        costoTransporte[ProvinciaFactory.GRANADA][ProvinciaFactory.PONTEVEDRA] = 146.58;
        costoTransporte[ProvinciaFactory.GRANADA][ProvinciaFactory.ALAVA] = 139.6;
        costoTransporte[ProvinciaFactory.GRANADA][ProvinciaFactory.GIPUZKOA] = 145;
        costoTransporte[ProvinciaFactory.GRANADA][ProvinciaFactory.BIZKAIA] = 136.21;
        costoTransporte[ProvinciaFactory.HUELVA][ProvinciaFactory.MADRID] = 78.28;
        costoTransporte[ProvinciaFactory.HUELVA][ProvinciaFactory.ALMERIA] = 97.95;
        costoTransporte[ProvinciaFactory.HUELVA][ProvinciaFactory.CADIZ] = 33.6;
        costoTransporte[ProvinciaFactory.HUELVA][ProvinciaFactory.CORDOBA] = 45.06;
        costoTransporte[ProvinciaFactory.HUELVA][ProvinciaFactory.GRANADA] = 89.73;
        costoTransporte[ProvinciaFactory.HUELVA][ProvinciaFactory.HUELVA] = 0;
        costoTransporte[ProvinciaFactory.HUELVA][ProvinciaFactory.JAEN] = 47.99;
        costoTransporte[ProvinciaFactory.HUELVA][ProvinciaFactory.MALAGA] = 54.83;
        costoTransporte[ProvinciaFactory.HUELVA][ProvinciaFactory.SEVILLA] = 14.63;
        costoTransporte[ProvinciaFactory.HUELVA][ProvinciaFactory.BARCELONA] = 145.96;
        costoTransporte[ProvinciaFactory.HUELVA][ProvinciaFactory.GIRONA] = 186.42;
        costoTransporte[ProvinciaFactory.HUELVA][ProvinciaFactory.LLEIDA] = 180.31;
        costoTransporte[ProvinciaFactory.HUELVA][ProvinciaFactory.TARRAGONA] = 169.23;
        costoTransporte[ProvinciaFactory.HUELVA][ProvinciaFactory.ALICANTE] = 88.49;
        costoTransporte[ProvinciaFactory.HUELVA][ProvinciaFactory.CASTELLON] = 80.69;
        costoTransporte[ProvinciaFactory.HUELVA][ProvinciaFactory.VALENCIA] = 67.84;
        costoTransporte[ProvinciaFactory.HUELVA][ProvinciaFactory.ACORUNA] = 116.16;
        costoTransporte[ProvinciaFactory.HUELVA][ProvinciaFactory.LUGO] = 131.45;
        costoTransporte[ProvinciaFactory.HUELVA][ProvinciaFactory.OURENSE] = 119.86;
        costoTransporte[ProvinciaFactory.HUELVA][ProvinciaFactory.PONTEVEDRA] = 125.41;
        costoTransporte[ProvinciaFactory.HUELVA][ProvinciaFactory.ALAVA] = 118.43;
        costoTransporte[ProvinciaFactory.HUELVA][ProvinciaFactory.GIPUZKOA] = 123.83;
        costoTransporte[ProvinciaFactory.HUELVA][ProvinciaFactory.BIZKAIA] = 115.04;
        costoTransporte[ProvinciaFactory.JAEN][ProvinciaFactory.MADRID] = 41.91;
        costoTransporte[ProvinciaFactory.JAEN][ProvinciaFactory.ALMERIA] = 86.25;
        costoTransporte[ProvinciaFactory.JAEN][ProvinciaFactory.CADIZ] = 44.58;
        costoTransporte[ProvinciaFactory.JAEN][ProvinciaFactory.CORDOBA] = 17.21;
        costoTransporte[ProvinciaFactory.JAEN][ProvinciaFactory.GRANADA] = 62.39;
        costoTransporte[ProvinciaFactory.JAEN][ProvinciaFactory.HUELVA] = 47.99;
        costoTransporte[ProvinciaFactory.JAEN][ProvinciaFactory.JAEN] = 0;
        costoTransporte[ProvinciaFactory.JAEN][ProvinciaFactory.MALAGA] = 56.73;
        costoTransporte[ProvinciaFactory.JAEN][ProvinciaFactory.SEVILLA] = 33.36;
        costoTransporte[ProvinciaFactory.JAEN][ProvinciaFactory.BARCELONA] = 115.63;
        costoTransporte[ProvinciaFactory.JAEN][ProvinciaFactory.GIRONA] = 147.42;
        costoTransporte[ProvinciaFactory.JAEN][ProvinciaFactory.LLEIDA] = 149.97;
        costoTransporte[ProvinciaFactory.JAEN][ProvinciaFactory.TARRAGONA] = 41.91;
        costoTransporte[ProvinciaFactory.JAEN][ProvinciaFactory.ALICANTE] = 55.55;
        costoTransporte[ProvinciaFactory.JAEN][ProvinciaFactory.CASTELLON] = 37.64;
        costoTransporte[ProvinciaFactory.JAEN][ProvinciaFactory.VALENCIA] = 34.9;
        costoTransporte[ProvinciaFactory.JAEN][ProvinciaFactory.ACORUNA] = 134.89;
        costoTransporte[ProvinciaFactory.JAEN][ProvinciaFactory.LUGO] = 150.18;
        costoTransporte[ProvinciaFactory.JAEN][ProvinciaFactory.OURENSE] = 138.59;
        costoTransporte[ProvinciaFactory.JAEN][ProvinciaFactory.PONTEVEDRA] = 144.14;
        costoTransporte[ProvinciaFactory.JAEN][ProvinciaFactory.ALAVA] = 137.16;
        costoTransporte[ProvinciaFactory.JAEN][ProvinciaFactory.GIPUZKOA] = 142.56;
        costoTransporte[ProvinciaFactory.JAEN][ProvinciaFactory.BIZKAIA] = 133.77;
        costoTransporte[ProvinciaFactory.MALAGA][ProvinciaFactory.MADRID] = 76.29;
        costoTransporte[ProvinciaFactory.MALAGA][ProvinciaFactory.ALMERIA] = 58.77;
        costoTransporte[ProvinciaFactory.MALAGA][ProvinciaFactory.CADIZ] = 64.33;
        costoTransporte[ProvinciaFactory.MALAGA][ProvinciaFactory.CORDOBA] = 39.51;
        costoTransporte[ProvinciaFactory.MALAGA][ProvinciaFactory.GRANADA] = 34.91;
        costoTransporte[ProvinciaFactory.MALAGA][ProvinciaFactory.HUELVA] = 54.83;
        costoTransporte[ProvinciaFactory.MALAGA][ProvinciaFactory.JAEN] = 56.73;
        costoTransporte[ProvinciaFactory.MALAGA][ProvinciaFactory.MALAGA] = 0;
        costoTransporte[ProvinciaFactory.MALAGA][ProvinciaFactory.SEVILLA] = 40.19;
        costoTransporte[ProvinciaFactory.MALAGA][ProvinciaFactory.BARCELONA] = 150.06;
        costoTransporte[ProvinciaFactory.MALAGA][ProvinciaFactory.GIRONA] = 172.8;
        costoTransporte[ProvinciaFactory.MALAGA][ProvinciaFactory.LLEIDA] = 79.74;
        costoTransporte[ProvinciaFactory.MALAGA][ProvinciaFactory.TARRAGONA] = 173.33;
        costoTransporte[ProvinciaFactory.MALAGA][ProvinciaFactory.ALICANTE] = 133.62;
        costoTransporte[ProvinciaFactory.MALAGA][ProvinciaFactory.CASTELLON] = 139.9;
        costoTransporte[ProvinciaFactory.MALAGA][ProvinciaFactory.VALENCIA] = 127.06;
        costoTransporte[ProvinciaFactory.MALAGA][ProvinciaFactory.ACORUNA] = 107.18;
        costoTransporte[ProvinciaFactory.MALAGA][ProvinciaFactory.LUGO] = 83.46;
        costoTransporte[ProvinciaFactory.MALAGA][ProvinciaFactory.OURENSE] = 145.42;
        costoTransporte[ProvinciaFactory.MALAGA][ProvinciaFactory.PONTEVEDRA] = 115.6;
        costoTransporte[ProvinciaFactory.MALAGA][ProvinciaFactory.ALAVA] = 143.99;
        costoTransporte[ProvinciaFactory.MALAGA][ProvinciaFactory.GIPUZKOA] = 149.39;
        costoTransporte[ProvinciaFactory.MALAGA][ProvinciaFactory.BIZKAIA] = 113.37;
        costoTransporte[ProvinciaFactory.SEVILLA][ProvinciaFactory.MADRID] = 69.7;
        costoTransporte[ProvinciaFactory.SEVILLA][ProvinciaFactory.ALMERIA] = 59.66;
        costoTransporte[ProvinciaFactory.SEVILLA][ProvinciaFactory.CADIZ] = 18.02;
        costoTransporte[ProvinciaFactory.SEVILLA][ProvinciaFactory.CORDOBA] = 23.98;
        costoTransporte[ProvinciaFactory.SEVILLA][ProvinciaFactory.GRANADA] = 35.8;
        costoTransporte[ProvinciaFactory.SEVILLA][ProvinciaFactory.HUELVA] = 14.63;
        costoTransporte[ProvinciaFactory.SEVILLA][ProvinciaFactory.JAEN] = 33.36;
        costoTransporte[ProvinciaFactory.SEVILLA][ProvinciaFactory.MALAGA] = 40.19;
        costoTransporte[ProvinciaFactory.SEVILLA][ProvinciaFactory.SEVILLA] = 0;
        costoTransporte[ProvinciaFactory.SEVILLA][ProvinciaFactory.BARCELONA] = 131.87;
        costoTransporte[ProvinciaFactory.SEVILLA][ProvinciaFactory.GIRONA] = 126.73;
        costoTransporte[ProvinciaFactory.SEVILLA][ProvinciaFactory.LLEIDA] = 80.06;
        costoTransporte[ProvinciaFactory.SEVILLA][ProvinciaFactory.TARRAGONA] = 66.82;
        costoTransporte[ProvinciaFactory.SEVILLA][ProvinciaFactory.ALICANTE] = 140.95;
        costoTransporte[ProvinciaFactory.SEVILLA][ProvinciaFactory.CASTELLON] = 41.73;
        costoTransporte[ProvinciaFactory.SEVILLA][ProvinciaFactory.VALENCIA] = 86.16;
        costoTransporte[ProvinciaFactory.SEVILLA][ProvinciaFactory.ACORUNA] = 101.53;
        costoTransporte[ProvinciaFactory.SEVILLA][ProvinciaFactory.LUGO] = 116.82;
        costoTransporte[ProvinciaFactory.SEVILLA][ProvinciaFactory.OURENSE] = 105.23;
        costoTransporte[ProvinciaFactory.SEVILLA][ProvinciaFactory.PONTEVEDRA] = 110.78;
        costoTransporte[ProvinciaFactory.SEVILLA][ProvinciaFactory.ALAVA] = 103.8;
        costoTransporte[ProvinciaFactory.SEVILLA][ProvinciaFactory.GIPUZKOA] = 109.2;
        costoTransporte[ProvinciaFactory.SEVILLA][ProvinciaFactory.BIZKAIA] = 100.41;
        costoTransporte[ProvinciaFactory.BARCELONA][ProvinciaFactory.MADRID] = 83.12;
        costoTransporte[ProvinciaFactory.BARCELONA][ProvinciaFactory.ALMERIA] = 57.05;
        costoTransporte[ProvinciaFactory.BARCELONA][ProvinciaFactory.CADIZ] = 121.53;
        costoTransporte[ProvinciaFactory.BARCELONA][ProvinciaFactory.CORDOBA] = 123.29;
        costoTransporte[ProvinciaFactory.BARCELONA][ProvinciaFactory.GRANADA] = 55.09;
        costoTransporte[ProvinciaFactory.BARCELONA][ProvinciaFactory.HUELVA] = 145.96;
        costoTransporte[ProvinciaFactory.BARCELONA][ProvinciaFactory.JAEN] = 115.63;
        costoTransporte[ProvinciaFactory.BARCELONA][ProvinciaFactory.MALAGA] = 150.06;
        costoTransporte[ProvinciaFactory.BARCELONA][ProvinciaFactory.SEVILLA] = 131.87;
        costoTransporte[ProvinciaFactory.BARCELONA][ProvinciaFactory.BARCELONA] = 0;
        costoTransporte[ProvinciaFactory.BARCELONA][ProvinciaFactory.GIRONA] = 24.16;
        costoTransporte[ProvinciaFactory.BARCELONA][ProvinciaFactory.LLEIDA] = 34.35;
        costoTransporte[ProvinciaFactory.BARCELONA][ProvinciaFactory.TARRAGONA] = 23.27;
        costoTransporte[ProvinciaFactory.BARCELONA][ProvinciaFactory.ALICANTE] = 32.21;
        costoTransporte[ProvinciaFactory.BARCELONA][ProvinciaFactory.CASTELLON] = 25.86;
        costoTransporte[ProvinciaFactory.BARCELONA][ProvinciaFactory.VALENCIA] = 29.65;
        costoTransporte[ProvinciaFactory.BARCELONA][ProvinciaFactory.ACORUNA] = 75.8;
        costoTransporte[ProvinciaFactory.BARCELONA][ProvinciaFactory.LUGO] = 73.37;
        costoTransporte[ProvinciaFactory.BARCELONA][ProvinciaFactory.OURENSE] = 59.86;
        costoTransporte[ProvinciaFactory.BARCELONA][ProvinciaFactory.PONTEVEDRA] = 79.69;
        costoTransporte[ProvinciaFactory.BARCELONA][ProvinciaFactory.ALAVA] = 41.2;
        costoTransporte[ProvinciaFactory.BARCELONA][ProvinciaFactory.GIPUZKOA] = 43.07;
        costoTransporte[ProvinciaFactory.BARCELONA][ProvinciaFactory.BIZKAIA] = 36.14;
        costoTransporte[ProvinciaFactory.GIRONA][ProvinciaFactory.MADRID] = 108.14;
        costoTransporte[ProvinciaFactory.GIRONA][ProvinciaFactory.ALMERIA] = 104.23;
        costoTransporte[ProvinciaFactory.GIRONA][ProvinciaFactory.CADIZ] = 158.46;
        costoTransporte[ProvinciaFactory.GIRONA][ProvinciaFactory.CORDOBA] = 97.94;
        costoTransporte[ProvinciaFactory.GIRONA][ProvinciaFactory.GRANADA] = 128.09;
        costoTransporte[ProvinciaFactory.GIRONA][ProvinciaFactory.HUELVA] = 186.42;
        costoTransporte[ProvinciaFactory.GIRONA][ProvinciaFactory.JAEN] = 147.42;
        costoTransporte[ProvinciaFactory.GIRONA][ProvinciaFactory.MALAGA] = 172.8;
        costoTransporte[ProvinciaFactory.GIRONA][ProvinciaFactory.SEVILLA] = 126.73;
        costoTransporte[ProvinciaFactory.GIRONA][ProvinciaFactory.BARCELONA] = 24.16;
        costoTransporte[ProvinciaFactory.GIRONA][ProvinciaFactory.GIRONA] = 0;
        costoTransporte[ProvinciaFactory.GIRONA][ProvinciaFactory.LLEIDA] = 37.73;
        costoTransporte[ProvinciaFactory.GIRONA][ProvinciaFactory.TARRAGONA] = 47.43;
        costoTransporte[ProvinciaFactory.GIRONA][ProvinciaFactory.ALICANTE] = 73.11;
        costoTransporte[ProvinciaFactory.GIRONA][ProvinciaFactory.CASTELLON] = 50.02;
        costoTransporte[ProvinciaFactory.GIRONA][ProvinciaFactory.VALENCIA] = 54.91;
        costoTransporte[ProvinciaFactory.GIRONA][ProvinciaFactory.ACORUNA] = 78.17;
        costoTransporte[ProvinciaFactory.GIRONA][ProvinciaFactory.LUGO] = 97.53;
        costoTransporte[ProvinciaFactory.GIRONA][ProvinciaFactory.OURENSE] = 84.02;
        costoTransporte[ProvinciaFactory.GIRONA][ProvinciaFactory.PONTEVEDRA] = 103.85;
        costoTransporte[ProvinciaFactory.GIRONA][ProvinciaFactory.ALAVA] = 65.36;
        costoTransporte[ProvinciaFactory.GIRONA][ProvinciaFactory.GIPUZKOA] = 67.23;
        costoTransporte[ProvinciaFactory.GIRONA][ProvinciaFactory.BIZKAIA] = 60.3;
        costoTransporte[ProvinciaFactory.LLEIDA][ProvinciaFactory.MADRID] = 62.78;
        costoTransporte[ProvinciaFactory.LLEIDA][ProvinciaFactory.ALMERIA] = 91.4;
        costoTransporte[ProvinciaFactory.LLEIDA][ProvinciaFactory.CADIZ] = 155.88;
        costoTransporte[ProvinciaFactory.LLEIDA][ProvinciaFactory.CORDOBA] = 75.64;
        costoTransporte[ProvinciaFactory.LLEIDA][ProvinciaFactory.GRANADA] = 89.44;
        costoTransporte[ProvinciaFactory.LLEIDA][ProvinciaFactory.HUELVA] = 180.31;
        costoTransporte[ProvinciaFactory.LLEIDA][ProvinciaFactory.JAEN] = 149.97;
        costoTransporte[ProvinciaFactory.LLEIDA][ProvinciaFactory.MALAGA] = 79.74;
        costoTransporte[ProvinciaFactory.LLEIDA][ProvinciaFactory.SEVILLA] = 80.06;
        costoTransporte[ProvinciaFactory.LLEIDA][ProvinciaFactory.BARCELONA] = 34.35;
        costoTransporte[ProvinciaFactory.LLEIDA][ProvinciaFactory.GIRONA] = 37.73;
        costoTransporte[ProvinciaFactory.LLEIDA][ProvinciaFactory.LLEIDA] = 0;
        costoTransporte[ProvinciaFactory.LLEIDA][ProvinciaFactory.TARRAGONA] = 20.51;
        costoTransporte[ProvinciaFactory.LLEIDA][ProvinciaFactory.ALICANTE] = 66.55;
        costoTransporte[ProvinciaFactory.LLEIDA][ProvinciaFactory.CASTELLON] = 60.2;
        costoTransporte[ProvinciaFactory.LLEIDA][ProvinciaFactory.VALENCIA] = 63.99;
        costoTransporte[ProvinciaFactory.LLEIDA][ProvinciaFactory.ACORUNA] = 57.96;
        costoTransporte[ProvinciaFactory.LLEIDA][ProvinciaFactory.LUGO] = 76.39;
        costoTransporte[ProvinciaFactory.LLEIDA][ProvinciaFactory.OURENSE] = 56.54;
        costoTransporte[ProvinciaFactory.LLEIDA][ProvinciaFactory.PONTEVEDRA] = 78;
        costoTransporte[ProvinciaFactory.LLEIDA][ProvinciaFactory.ALAVA] = 29.7;
        costoTransporte[ProvinciaFactory.LLEIDA][ProvinciaFactory.GIPUZKOA] = 31.74;
        costoTransporte[ProvinciaFactory.LLEIDA][ProvinciaFactory.BIZKAIA] = 27.23;
        costoTransporte[ProvinciaFactory.TARRAGONA][ProvinciaFactory.MADRID] = 81.84;
        costoTransporte[ProvinciaFactory.TARRAGONA][ProvinciaFactory.ALMERIA] = 80.32;
        costoTransporte[ProvinciaFactory.TARRAGONA][ProvinciaFactory.CADIZ] = 144.8;
        costoTransporte[ProvinciaFactory.TARRAGONA][ProvinciaFactory.CORDOBA] = 64.68;
        costoTransporte[ProvinciaFactory.TARRAGONA][ProvinciaFactory.GRANADA] = 78.36;
        costoTransporte[ProvinciaFactory.TARRAGONA][ProvinciaFactory.HUELVA] = 169.23;
        costoTransporte[ProvinciaFactory.TARRAGONA][ProvinciaFactory.JAEN] = 41.91;
        costoTransporte[ProvinciaFactory.TARRAGONA][ProvinciaFactory.MALAGA] = 173.33;
        costoTransporte[ProvinciaFactory.TARRAGONA][ProvinciaFactory.SEVILLA] = 66.82;
        costoTransporte[ProvinciaFactory.TARRAGONA][ProvinciaFactory.BARCELONA] = 23.27;
        costoTransporte[ProvinciaFactory.TARRAGONA][ProvinciaFactory.GIRONA] = 47.43;
        costoTransporte[ProvinciaFactory.TARRAGONA][ProvinciaFactory.LLEIDA] = 20.51;
        costoTransporte[ProvinciaFactory.TARRAGONA][ProvinciaFactory.TARRAGONA] = 0;
        costoTransporte[ProvinciaFactory.TARRAGONA][ProvinciaFactory.ALICANTE] = 28.91;
        costoTransporte[ProvinciaFactory.TARRAGONA][ProvinciaFactory.CASTELLON] = 20.95;
        costoTransporte[ProvinciaFactory.TARRAGONA][ProvinciaFactory.VALENCIA] = 24.99;
        costoTransporte[ProvinciaFactory.TARRAGONA][ProvinciaFactory.ACORUNA] = 99.07;
        costoTransporte[ProvinciaFactory.TARRAGONA][ProvinciaFactory.LUGO] = 96.64;
        costoTransporte[ProvinciaFactory.TARRAGONA][ProvinciaFactory.OURENSE] = 83.13;
        costoTransporte[ProvinciaFactory.TARRAGONA][ProvinciaFactory.PONTEVEDRA] = 102.96;
        costoTransporte[ProvinciaFactory.TARRAGONA][ProvinciaFactory.ALAVA] = 50.21;
        costoTransporte[ProvinciaFactory.TARRAGONA][ProvinciaFactory.GIPUZKOA] = 52.25;
        costoTransporte[ProvinciaFactory.TARRAGONA][ProvinciaFactory.BIZKAIA] = 47.74;
        costoTransporte[ProvinciaFactory.ALICANTE][ProvinciaFactory.MADRID] = 55.98;
        costoTransporte[ProvinciaFactory.ALICANTE][ProvinciaFactory.ALMERIA] = 69.97;
        costoTransporte[ProvinciaFactory.ALICANTE][ProvinciaFactory.CADIZ] = 91.08;
        costoTransporte[ProvinciaFactory.ALICANTE][ProvinciaFactory.CORDOBA] = 63.68;
        costoTransporte[ProvinciaFactory.ALICANTE][ProvinciaFactory.GRANADA] = 93.83;
        costoTransporte[ProvinciaFactory.ALICANTE][ProvinciaFactory.HUELVA] = 88.49;
        costoTransporte[ProvinciaFactory.ALICANTE][ProvinciaFactory.JAEN] = 55.55;
        costoTransporte[ProvinciaFactory.ALICANTE][ProvinciaFactory.MALAGA] = 133.62;
        costoTransporte[ProvinciaFactory.ALICANTE][ProvinciaFactory.SEVILLA] = 140.95;
        costoTransporte[ProvinciaFactory.ALICANTE][ProvinciaFactory.BARCELONA] = 32.21;
        costoTransporte[ProvinciaFactory.ALICANTE][ProvinciaFactory.GIRONA] = 73.11;
        costoTransporte[ProvinciaFactory.ALICANTE][ProvinciaFactory.LLEIDA] = 66.55;
        costoTransporte[ProvinciaFactory.ALICANTE][ProvinciaFactory.TARRAGONA] = 28.91;
        costoTransporte[ProvinciaFactory.ALICANTE][ProvinciaFactory.ALICANTE] = 0;
        costoTransporte[ProvinciaFactory.ALICANTE][ProvinciaFactory.CASTELLON] = 23.89;
        costoTransporte[ProvinciaFactory.ALICANTE][ProvinciaFactory.VALENCIA] = 20.65;
        costoTransporte[ProvinciaFactory.ALICANTE][ProvinciaFactory.ACORUNA] = 79.42;
        costoTransporte[ProvinciaFactory.ALICANTE][ProvinciaFactory.LUGO] = 100.39;
        costoTransporte[ProvinciaFactory.ALICANTE][ProvinciaFactory.OURENSE] = 91.51;
        costoTransporte[ProvinciaFactory.ALICANTE][ProvinciaFactory.PONTEVEDRA] = 79.07;
        costoTransporte[ProvinciaFactory.ALICANTE][ProvinciaFactory.ALAVA] = 84.41;
        costoTransporte[ProvinciaFactory.ALICANTE][ProvinciaFactory.GIPUZKOA] = 95.48;
        costoTransporte[ProvinciaFactory.ALICANTE][ProvinciaFactory.BIZKAIA] = 109.78;
        costoTransporte[ProvinciaFactory.CASTELLON][ProvinciaFactory.MADRID] = 47.14;
        costoTransporte[ProvinciaFactory.CASTELLON][ProvinciaFactory.ALMERIA] = 62.17;
        costoTransporte[ProvinciaFactory.CASTELLON][ProvinciaFactory.CADIZ] = 83.28;
        costoTransporte[ProvinciaFactory.CASTELLON][ProvinciaFactory.CORDOBA] = 40.13;
        costoTransporte[ProvinciaFactory.CASTELLON][ProvinciaFactory.GRANADA] = 86.03;
        costoTransporte[ProvinciaFactory.CASTELLON][ProvinciaFactory.HUELVA] = 80.69;
        costoTransporte[ProvinciaFactory.CASTELLON][ProvinciaFactory.JAEN] = 37.64;
        costoTransporte[ProvinciaFactory.CASTELLON][ProvinciaFactory.MALAGA] = 139.9;
        costoTransporte[ProvinciaFactory.CASTELLON][ProvinciaFactory.SEVILLA] = 41.73;
        costoTransporte[ProvinciaFactory.CASTELLON][ProvinciaFactory.BARCELONA] = 25.86;
        costoTransporte[ProvinciaFactory.CASTELLON][ProvinciaFactory.GIRONA] = 50.02;
        costoTransporte[ProvinciaFactory.CASTELLON][ProvinciaFactory.LLEIDA] = 60.2;
        costoTransporte[ProvinciaFactory.CASTELLON][ProvinciaFactory.TARRAGONA] = 20.95;
        costoTransporte[ProvinciaFactory.CASTELLON][ProvinciaFactory.ALICANTE] = 23.89;
        costoTransporte[ProvinciaFactory.CASTELLON][ProvinciaFactory.CASTELLON] = 0;
        costoTransporte[ProvinciaFactory.CASTELLON][ProvinciaFactory.VALENCIA] = 12.85;
        costoTransporte[ProvinciaFactory.CASTELLON][ProvinciaFactory.ACORUNA] = 95.93;
        costoTransporte[ProvinciaFactory.CASTELLON][ProvinciaFactory.LUGO] = 91.54;
        costoTransporte[ProvinciaFactory.CASTELLON][ProvinciaFactory.OURENSE] = 82.67;
        costoTransporte[ProvinciaFactory.CASTELLON][ProvinciaFactory.PONTEVEDRA] = 88.22;
        costoTransporte[ProvinciaFactory.CASTELLON][ProvinciaFactory.ALAVA] = 96.2;
        costoTransporte[ProvinciaFactory.CASTELLON][ProvinciaFactory.GIPUZKOA] = 86.64;
        costoTransporte[ProvinciaFactory.CASTELLON][ProvinciaFactory.BIZKAIA] = 100.94;
        costoTransporte[ProvinciaFactory.VALENCIA][ProvinciaFactory.MADRID] = 53.34;
        costoTransporte[ProvinciaFactory.VALENCIA][ProvinciaFactory.ALMERIA] = 49.32;
        costoTransporte[ProvinciaFactory.VALENCIA][ProvinciaFactory.CADIZ] = 70.43;
        costoTransporte[ProvinciaFactory.VALENCIA][ProvinciaFactory.CORDOBA] = 43.03;
        costoTransporte[ProvinciaFactory.VALENCIA][ProvinciaFactory.GRANADA] = 73.18;
        costoTransporte[ProvinciaFactory.VALENCIA][ProvinciaFactory.HUELVA] = 67.84;
        costoTransporte[ProvinciaFactory.VALENCIA][ProvinciaFactory.JAEN] = 34.9;
        costoTransporte[ProvinciaFactory.VALENCIA][ProvinciaFactory.MALAGA] = 127.06;
        costoTransporte[ProvinciaFactory.VALENCIA][ProvinciaFactory.SEVILLA] = 86.16;
        costoTransporte[ProvinciaFactory.VALENCIA][ProvinciaFactory.BARCELONA] = 29.65;
        costoTransporte[ProvinciaFactory.VALENCIA][ProvinciaFactory.GIRONA] = 54.91;
        costoTransporte[ProvinciaFactory.VALENCIA][ProvinciaFactory.LLEIDA] = 63.99;
        costoTransporte[ProvinciaFactory.VALENCIA][ProvinciaFactory.TARRAGONA] = 24.99;
        costoTransporte[ProvinciaFactory.VALENCIA][ProvinciaFactory.ALICANTE] = 20.65;
        costoTransporte[ProvinciaFactory.VALENCIA][ProvinciaFactory.CASTELLON] = 12.85;
        costoTransporte[ProvinciaFactory.VALENCIA][ProvinciaFactory.VALENCIA] = 0;
        costoTransporte[ProvinciaFactory.VALENCIA][ProvinciaFactory.ACORUNA] = 53.6;
        costoTransporte[ProvinciaFactory.VALENCIA][ProvinciaFactory.LUGO] = 73.07;
        costoTransporte[ProvinciaFactory.VALENCIA][ProvinciaFactory.OURENSE] = 88.87;
        costoTransporte[ProvinciaFactory.VALENCIA][ProvinciaFactory.PONTEVEDRA] = 86.02;
        costoTransporte[ProvinciaFactory.VALENCIA][ProvinciaFactory.ALAVA] = 59.68;
        costoTransporte[ProvinciaFactory.VALENCIA][ProvinciaFactory.GIPUZKOA] = 92.84;
        costoTransporte[ProvinciaFactory.VALENCIA][ProvinciaFactory.BIZKAIA] = 107.14;
        costoTransporte[ProvinciaFactory.ACORUNA][ProvinciaFactory.MADRID] = 48.79;
        costoTransporte[ProvinciaFactory.ACORUNA][ProvinciaFactory.ALMERIA] = 161.19;
        costoTransporte[ProvinciaFactory.ACORUNA][ProvinciaFactory.CADIZ] = 73.54;
        costoTransporte[ProvinciaFactory.ACORUNA][ProvinciaFactory.CORDOBA] = 125.51;
        costoTransporte[ProvinciaFactory.ACORUNA][ProvinciaFactory.GRANADA] = 137.33;
        costoTransporte[ProvinciaFactory.ACORUNA][ProvinciaFactory.HUELVA] = 116.16;
        costoTransporte[ProvinciaFactory.ACORUNA][ProvinciaFactory.JAEN] = 134.89;
        costoTransporte[ProvinciaFactory.ACORUNA][ProvinciaFactory.MALAGA] = 107.18;
        costoTransporte[ProvinciaFactory.ACORUNA][ProvinciaFactory.SEVILLA] = 101.53;
        costoTransporte[ProvinciaFactory.ACORUNA][ProvinciaFactory.BARCELONA] = 75.8;
        costoTransporte[ProvinciaFactory.ACORUNA][ProvinciaFactory.GIRONA] = 78.17;
        costoTransporte[ProvinciaFactory.ACORUNA][ProvinciaFactory.LLEIDA] = 57.96;
        costoTransporte[ProvinciaFactory.ACORUNA][ProvinciaFactory.TARRAGONA] = 99.07;
        costoTransporte[ProvinciaFactory.ACORUNA][ProvinciaFactory.ALICANTE] = 79.42;
        costoTransporte[ProvinciaFactory.ACORUNA][ProvinciaFactory.CASTELLON] = 95.93;
        costoTransporte[ProvinciaFactory.ACORUNA][ProvinciaFactory.VALENCIA] = 53.6;
        costoTransporte[ProvinciaFactory.ACORUNA][ProvinciaFactory.ACORUNA] = 0;
        costoTransporte[ProvinciaFactory.ACORUNA][ProvinciaFactory.LUGO] = 13.09;
        costoTransporte[ProvinciaFactory.ACORUNA][ProvinciaFactory.OURENSE] = 26.8;
        costoTransporte[ProvinciaFactory.ACORUNA][ProvinciaFactory.PONTEVEDRA] = 17.61;
        costoTransporte[ProvinciaFactory.ACORUNA][ProvinciaFactory.ALAVA] = 45.09;
        costoTransporte[ProvinciaFactory.ACORUNA][ProvinciaFactory.GIPUZKOA] = 54.45;
        costoTransporte[ProvinciaFactory.ACORUNA][ProvinciaFactory.BIZKAIA] = 60.88;
        costoTransporte[ProvinciaFactory.LUGO][ProvinciaFactory.MADRID] = 44.41;
        costoTransporte[ProvinciaFactory.LUGO][ProvinciaFactory.ALMERIA] = 176.48;
        costoTransporte[ProvinciaFactory.LUGO][ProvinciaFactory.CADIZ] = 134.84;
        costoTransporte[ProvinciaFactory.LUGO][ProvinciaFactory.CORDOBA] = 140.8;
        costoTransporte[ProvinciaFactory.LUGO][ProvinciaFactory.GRANADA] = 152.62;
        costoTransporte[ProvinciaFactory.LUGO][ProvinciaFactory.HUELVA] = 131.45;
        costoTransporte[ProvinciaFactory.LUGO][ProvinciaFactory.JAEN] = 150.18;
        costoTransporte[ProvinciaFactory.LUGO][ProvinciaFactory.MALAGA] = 83.46;
        costoTransporte[ProvinciaFactory.LUGO][ProvinciaFactory.SEVILLA] = 116.82;
        costoTransporte[ProvinciaFactory.LUGO][ProvinciaFactory.BARCELONA] = 73.37;
        costoTransporte[ProvinciaFactory.LUGO][ProvinciaFactory.GIRONA] = 97.53;
        costoTransporte[ProvinciaFactory.LUGO][ProvinciaFactory.LLEIDA] = 76.39;
        costoTransporte[ProvinciaFactory.LUGO][ProvinciaFactory.TARRAGONA] = 96.64;
        costoTransporte[ProvinciaFactory.LUGO][ProvinciaFactory.ALICANTE] = 100.39;
        costoTransporte[ProvinciaFactory.LUGO][ProvinciaFactory.CASTELLON] = 91.54;
        costoTransporte[ProvinciaFactory.LUGO][ProvinciaFactory.VALENCIA] = 73.07;
        costoTransporte[ProvinciaFactory.LUGO][ProvinciaFactory.ACORUNA] = 13.09;
        costoTransporte[ProvinciaFactory.LUGO][ProvinciaFactory.LUGO] = 0;
        costoTransporte[ProvinciaFactory.LUGO][ProvinciaFactory.OURENSE] = 11.37;
        costoTransporte[ProvinciaFactory.LUGO][ProvinciaFactory.PONTEVEDRA] = 28.74;
        costoTransporte[ProvinciaFactory.LUGO][ProvinciaFactory.ALAVA] = 39.29;
        costoTransporte[ProvinciaFactory.LUGO][ProvinciaFactory.GIPUZKOA] = 51;
        costoTransporte[ProvinciaFactory.LUGO][ProvinciaFactory.BIZKAIA] = 47.79;
        costoTransporte[ProvinciaFactory.OURENSE][ProvinciaFactory.MADRID] = 35.53;
        costoTransporte[ProvinciaFactory.OURENSE][ProvinciaFactory.ALMERIA] = 164.89;
        costoTransporte[ProvinciaFactory.OURENSE][ProvinciaFactory.CADIZ] = 123.25;
        costoTransporte[ProvinciaFactory.OURENSE][ProvinciaFactory.CORDOBA] = 129.21;
        costoTransporte[ProvinciaFactory.OURENSE][ProvinciaFactory.GRANADA] = 141.03;
        costoTransporte[ProvinciaFactory.OURENSE][ProvinciaFactory.HUELVA] = 119.86;
        costoTransporte[ProvinciaFactory.OURENSE][ProvinciaFactory.JAEN] = 138.59;
        costoTransporte[ProvinciaFactory.OURENSE][ProvinciaFactory.MALAGA] = 145.42;
        costoTransporte[ProvinciaFactory.OURENSE][ProvinciaFactory.SEVILLA] = 105.23;
        costoTransporte[ProvinciaFactory.OURENSE][ProvinciaFactory.BARCELONA] = 59.86;
        costoTransporte[ProvinciaFactory.OURENSE][ProvinciaFactory.GIRONA] = 84.02;
        costoTransporte[ProvinciaFactory.OURENSE][ProvinciaFactory.LLEIDA] = 56.54;
        costoTransporte[ProvinciaFactory.OURENSE][ProvinciaFactory.TARRAGONA] = 83.13;
        costoTransporte[ProvinciaFactory.OURENSE][ProvinciaFactory.ALICANTE] = 91.51;
        costoTransporte[ProvinciaFactory.OURENSE][ProvinciaFactory.CASTELLON] = 82.67;
        costoTransporte[ProvinciaFactory.OURENSE][ProvinciaFactory.VALENCIA] = 88.87;
        costoTransporte[ProvinciaFactory.OURENSE][ProvinciaFactory.ACORUNA] = 26.8;
        costoTransporte[ProvinciaFactory.OURENSE][ProvinciaFactory.LUGO] = 11.37;
        costoTransporte[ProvinciaFactory.OURENSE][ProvinciaFactory.OURENSE] = 0;
        costoTransporte[ProvinciaFactory.OURENSE][ProvinciaFactory.PONTEVEDRA] = 17.37;
        costoTransporte[ProvinciaFactory.OURENSE][ProvinciaFactory.ALAVA] = 41.43;
        costoTransporte[ProvinciaFactory.OURENSE][ProvinciaFactory.GIPUZKOA] = 52.19;
        costoTransporte[ProvinciaFactory.OURENSE][ProvinciaFactory.BIZKAIA] = 50.17;
        costoTransporte[ProvinciaFactory.PONTEVEDRA][ProvinciaFactory.MADRID] = 41.08;
        costoTransporte[ProvinciaFactory.PONTEVEDRA][ProvinciaFactory.ALMERIA] = 170.44;
        costoTransporte[ProvinciaFactory.PONTEVEDRA][ProvinciaFactory.CADIZ] = 73.18;
        costoTransporte[ProvinciaFactory.PONTEVEDRA][ProvinciaFactory.CORDOBA] = 134.76;
        costoTransporte[ProvinciaFactory.PONTEVEDRA][ProvinciaFactory.GRANADA] = 146.58;
        costoTransporte[ProvinciaFactory.PONTEVEDRA][ProvinciaFactory.HUELVA] = 125.41;
        costoTransporte[ProvinciaFactory.PONTEVEDRA][ProvinciaFactory.JAEN] = 144.14;
        costoTransporte[ProvinciaFactory.PONTEVEDRA][ProvinciaFactory.MALAGA] = 115.6;
        costoTransporte[ProvinciaFactory.PONTEVEDRA][ProvinciaFactory.SEVILLA] = 110.78;
        costoTransporte[ProvinciaFactory.PONTEVEDRA][ProvinciaFactory.BARCELONA] = 79.69;
        costoTransporte[ProvinciaFactory.PONTEVEDRA][ProvinciaFactory.GIRONA] = 103.85;
        costoTransporte[ProvinciaFactory.PONTEVEDRA][ProvinciaFactory.LLEIDA] = 78;
        costoTransporte[ProvinciaFactory.PONTEVEDRA][ProvinciaFactory.TARRAGONA] = 102.96;
        costoTransporte[ProvinciaFactory.PONTEVEDRA][ProvinciaFactory.ALICANTE] = 79.07;
        costoTransporte[ProvinciaFactory.PONTEVEDRA][ProvinciaFactory.CASTELLON] = 88.22;
        costoTransporte[ProvinciaFactory.PONTEVEDRA][ProvinciaFactory.VALENCIA] = 86.02;
        costoTransporte[ProvinciaFactory.PONTEVEDRA][ProvinciaFactory.ACORUNA] = 17.61;
        costoTransporte[ProvinciaFactory.PONTEVEDRA][ProvinciaFactory.LUGO] = 28.74;
        costoTransporte[ProvinciaFactory.PONTEVEDRA][ProvinciaFactory.OURENSE] = 17.37;
        costoTransporte[ProvinciaFactory.PONTEVEDRA][ProvinciaFactory.PONTEVEDRA] = 0;
        costoTransporte[ProvinciaFactory.PONTEVEDRA][ProvinciaFactory.ALAVA] = 68.03;
        costoTransporte[ProvinciaFactory.PONTEVEDRA][ProvinciaFactory.GIPUZKOA] = 54.1;
        costoTransporte[ProvinciaFactory.PONTEVEDRA][ProvinciaFactory.BIZKAIA] = 52.91;
        costoTransporte[ProvinciaFactory.ALAVA][ProvinciaFactory.MADRID] = 49.07;
        costoTransporte[ProvinciaFactory.ALAVA][ProvinciaFactory.ALMERIA] = 163.46;
        costoTransporte[ProvinciaFactory.ALAVA][ProvinciaFactory.CADIZ] = 121.82;
        costoTransporte[ProvinciaFactory.ALAVA][ProvinciaFactory.CORDOBA] = 127.78;
        costoTransporte[ProvinciaFactory.ALAVA][ProvinciaFactory.GRANADA] = 139.6;
        costoTransporte[ProvinciaFactory.ALAVA][ProvinciaFactory.HUELVA] = 118.43;
        costoTransporte[ProvinciaFactory.ALAVA][ProvinciaFactory.JAEN] = 137.16;
        costoTransporte[ProvinciaFactory.ALAVA][ProvinciaFactory.MALAGA] = 143.99;
        costoTransporte[ProvinciaFactory.ALAVA][ProvinciaFactory.SEVILLA] = 103.8;
        costoTransporte[ProvinciaFactory.ALAVA][ProvinciaFactory.BARCELONA] = 41.2;
        costoTransporte[ProvinciaFactory.ALAVA][ProvinciaFactory.GIRONA] = 65.36;
        costoTransporte[ProvinciaFactory.ALAVA][ProvinciaFactory.LLEIDA] = 29.7;
        costoTransporte[ProvinciaFactory.ALAVA][ProvinciaFactory.TARRAGONA] = 50.21;
        costoTransporte[ProvinciaFactory.ALAVA][ProvinciaFactory.ALICANTE] = 84.41;
        costoTransporte[ProvinciaFactory.ALAVA][ProvinciaFactory.CASTELLON] = 96.2;
        costoTransporte[ProvinciaFactory.ALAVA][ProvinciaFactory.VALENCIA] = 59.68;
        costoTransporte[ProvinciaFactory.ALAVA][ProvinciaFactory.ACORUNA] = 45.09;
        costoTransporte[ProvinciaFactory.ALAVA][ProvinciaFactory.LUGO] = 39.29;
        costoTransporte[ProvinciaFactory.ALAVA][ProvinciaFactory.OURENSE] = 41.43;
        costoTransporte[ProvinciaFactory.ALAVA][ProvinciaFactory.PONTEVEDRA] = 68.03;
        costoTransporte[ProvinciaFactory.ALAVA][ProvinciaFactory.ALAVA] = 0;
        costoTransporte[ProvinciaFactory.ALAVA][ProvinciaFactory.GIPUZKOA] = 16.34;
        costoTransporte[ProvinciaFactory.ALAVA][ProvinciaFactory.BIZKAIA] = 43.71;
        costoTransporte[ProvinciaFactory.GIPUZKOA][ProvinciaFactory.MADRID] = 39.5;
        costoTransporte[ProvinciaFactory.GIPUZKOA][ProvinciaFactory.ALMERIA] = 168.86;
        costoTransporte[ProvinciaFactory.GIPUZKOA][ProvinciaFactory.CADIZ] = 127.22;
        costoTransporte[ProvinciaFactory.GIPUZKOA][ProvinciaFactory.CORDOBA] = 133.18;
        costoTransporte[ProvinciaFactory.GIPUZKOA][ProvinciaFactory.GRANADA] = 145;
        costoTransporte[ProvinciaFactory.GIPUZKOA][ProvinciaFactory.HUELVA] = 123.83;
        costoTransporte[ProvinciaFactory.GIPUZKOA][ProvinciaFactory.JAEN] = 142.56;
        costoTransporte[ProvinciaFactory.GIPUZKOA][ProvinciaFactory.MALAGA] = 149.39;
        costoTransporte[ProvinciaFactory.GIPUZKOA][ProvinciaFactory.SEVILLA] = 109.2;
        costoTransporte[ProvinciaFactory.GIPUZKOA][ProvinciaFactory.BARCELONA] = 43.07;
        costoTransporte[ProvinciaFactory.GIPUZKOA][ProvinciaFactory.GIRONA] = 67.23;
        costoTransporte[ProvinciaFactory.GIPUZKOA][ProvinciaFactory.LLEIDA] = 31.74;
        costoTransporte[ProvinciaFactory.GIPUZKOA][ProvinciaFactory.TARRAGONA] = 52.25;
        costoTransporte[ProvinciaFactory.GIPUZKOA][ProvinciaFactory.ALICANTE] = 95.48;
        costoTransporte[ProvinciaFactory.GIPUZKOA][ProvinciaFactory.CASTELLON] = 86.64;
        costoTransporte[ProvinciaFactory.GIPUZKOA][ProvinciaFactory.VALENCIA] = 92.84;
        costoTransporte[ProvinciaFactory.GIPUZKOA][ProvinciaFactory.ACORUNA] = 54.45;
        costoTransporte[ProvinciaFactory.GIPUZKOA][ProvinciaFactory.LUGO] = 51;
        costoTransporte[ProvinciaFactory.GIPUZKOA][ProvinciaFactory.OURENSE] = 52.19;
        costoTransporte[ProvinciaFactory.GIPUZKOA][ProvinciaFactory.PONTEVEDRA] = 54.1;
        costoTransporte[ProvinciaFactory.GIPUZKOA][ProvinciaFactory.ALAVA] = 16.34;
        costoTransporte[ProvinciaFactory.GIPUZKOA][ProvinciaFactory.GIPUZKOA] = 0;
        costoTransporte[ProvinciaFactory.GIPUZKOA][ProvinciaFactory.BIZKAIA] = 27.37;
        costoTransporte[ProvinciaFactory.BIZKAIA][ProvinciaFactory.MADRID] = 53.8;
        costoTransporte[ProvinciaFactory.BIZKAIA][ProvinciaFactory.ALMERIA] = 160.07;
        costoTransporte[ProvinciaFactory.BIZKAIA][ProvinciaFactory.CADIZ] = 118.43;
        costoTransporte[ProvinciaFactory.BIZKAIA][ProvinciaFactory.CORDOBA] = 124.39;
        costoTransporte[ProvinciaFactory.BIZKAIA][ProvinciaFactory.GRANADA] = 136.21;
        costoTransporte[ProvinciaFactory.BIZKAIA][ProvinciaFactory.HUELVA] = 115.04;
        costoTransporte[ProvinciaFactory.BIZKAIA][ProvinciaFactory.JAEN] = 133.77;
        costoTransporte[ProvinciaFactory.BIZKAIA][ProvinciaFactory.MALAGA] = 113.37;
        costoTransporte[ProvinciaFactory.BIZKAIA][ProvinciaFactory.SEVILLA] = 100.41;
        costoTransporte[ProvinciaFactory.BIZKAIA][ProvinciaFactory.BARCELONA] = 36.14;
        costoTransporte[ProvinciaFactory.BIZKAIA][ProvinciaFactory.GIRONA] = 60.3;
        costoTransporte[ProvinciaFactory.BIZKAIA][ProvinciaFactory.LLEIDA] = 27.23;
        costoTransporte[ProvinciaFactory.BIZKAIA][ProvinciaFactory.TARRAGONA] = 47.74;
        costoTransporte[ProvinciaFactory.BIZKAIA][ProvinciaFactory.ALICANTE] = 109.78;
        costoTransporte[ProvinciaFactory.BIZKAIA][ProvinciaFactory.CASTELLON] = 100.94;
        costoTransporte[ProvinciaFactory.BIZKAIA][ProvinciaFactory.VALENCIA] = 107.14;
        costoTransporte[ProvinciaFactory.BIZKAIA][ProvinciaFactory.ACORUNA] = 60.88;
        costoTransporte[ProvinciaFactory.BIZKAIA][ProvinciaFactory.LUGO] = 47.79;
        costoTransporte[ProvinciaFactory.BIZKAIA][ProvinciaFactory.OURENSE] = 50.17;
        costoTransporte[ProvinciaFactory.BIZKAIA][ProvinciaFactory.PONTEVEDRA] = 52.91;
        costoTransporte[ProvinciaFactory.BIZKAIA][ProvinciaFactory.ALAVA] = 43.71;
        costoTransporte[ProvinciaFactory.BIZKAIA][ProvinciaFactory.GIPUZKOA] = 27.37;
        costoTransporte[ProvinciaFactory.BIZKAIA][ProvinciaFactory.BIZKAIA] = 0;
    }
}
